### ISSUE TITLE
CTP接口的SPI函数使用Event传递消息的考虑

### ISSUE THREAD

**Issue by dice2019** [zc8424/LazzyQuant#11]
我看了些文章，都说QT要用信号和槽来连接两个事件。
你的软件在CTradeHandler中采用的是QCoreApplication::postEvent。
请教一下，具体考虑是什么？初学，不懂，望见谅！
BTW：我正在重载API，但不知道用什么方式和后台线程通讯。
看你的实现有点复杂，所有纠结了：）

**Comment by zc8424** [comment]
CTradeHandler这个类没有继承QObject，所以用不了信号和槽。
所有的Spi接口函数都是在一个单独的线程里被调用的，所以不能在里面干太多的事(类似中断服务函数)，必须把数据转发出去，在主线程里再处理。
信号和槽之间的连接可以动态的connect/disconnect，非常灵活，但在这里也用不上，CTradeHandler类就负责把接收到的数据用postEvent发到事件队列就好了。
其实跨线程的信号和槽机制本质上也是通过事件来实现的。
