### ISSUE TITLE
no where can find header file "market_watcher_adaptor.h"

### ISSUE THREAD

**Issue by ZhongminJin** [zc8424/LazzyQuant#14]
Under the market_watch submodule, `market_watcher_dbus.cpp` used `#include "market_watcher_adaptor.h"
 
This head file and secure file can't find anywhere. Hence I can't compile the project. Any hint of his situation?

**Comment by zc8424** [comment]
Hi, "market_wather_adaptor.h" will be generated automatically by "qdbusxml2cpp" which is a tool provided by Qt. And "market_watcher_adaptor.cpp" as well. "qmake" will take care of these things for you. All you need to do is just like compiling a normal Qt project. Seems you are new to Qt, right? Please take some time to read the documents in the Qt "assistant" tool. It helps.

**Comment by ZhongminJin** [comment]
Thanks for your command.  I just realized that those `adaptor` files were generated by qdbusxml2cpp and I was just re-organized your src files by CMake which I am more familiar with. And the qmake tool can't go throng even on my ubuntu 18 with some error.  Now I have learned more with qt creator and d-bus.  I will try to dig into the build output and may need your advice later :).
