### ISSUE TITLE
error: C2065: “qOverload”: 未声明的标识符 qt5.12.3请问如何处理

### ISSUE THREAD

**Issue by alexfordc** [zc8424/LazzyQuant#15]
D:\quant\ctp\LazzyQuant-master\LazzyQuant-master\option_arbitrageur\option_arbitrageur_dbus.cpp:48: error: C2065: “qOverload”: 未声明的标识符

**Comment by alexfordc** [comment]
qOverload not defined for MSVC compiler
https://bugreports.qt.io/browse/QTBUG-61667

**Comment by zc8424** [comment]
我目前使用的是Qt 5.12.6 + MSVC 2017 v15.9.23  没有这个问题
