### ISSUE TITLE
关于部署中遇到的问题

### ISSUE THREAD

**Issue by hellobiek** [zc8424/LazzyQuant#18]
1、linux中的common.ini里面需要的飞狐交易师软件文件可否给出一个样本？
        电脑是linux环境，无法安装飞狐交易师软件，只能手工配置。
        我自己也下载了一个飞狐交易师，没有看到相关的路径。

**Comment by zc8424** [comment]
最新代码已不再需要common.ini，参考随0.5版发布的配置文件 https://github.com/zc8424/LazzyQuant/releases/tag/v0.5
