### ISSUE TITLE
CtpExecuter中的仓位字段为什么有四个

### ISSUE THREAD

**Issue by dice2019** [zc8424/LazzyQuant#9]
请教，CtpExecuter类中为什么有四个仓位字段，分别代表什么意思：   
 QMap<QString, int> ydLongPositions;
 QMap<QString, int> ydShortPositions;
 QMap<QString, int> tdLongPositions;
 QMap<QString, int> tdShortPositions;
BTW: 我以为只需要一个，谢谢

**Comment by zc8424** [comment]
yd 即 yesterday, 代表昨仓。
td 即 Today, 代表今仓。
Long 是多头的意思，Short是空头的意思。
组合起来所以每个合约都有4项持仓数量。
